<?php
// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Returns an array of media-related Font Awesome 6.7.2 Free icons for the BRMedia icon picker
 * @return array Icon class => Label
 */
function brmedia_get_media_icons() {
    return [
        // Playback Controls
        'fas fa-play' => 'Play',
        'fas fa-pause' => 'Pause',
        'fas fa-stop' => 'Stop',
        'fas fa-forward' => 'Fast Forward',
        'fas fa-backward' => 'Rewind',
        'fas fa-step-forward' => 'Next Track',
        'fas fa-step-backward' => 'Previous Track',
        'fas fa-play-circle' => 'Play Circle',
        'fas fa-pause-circle' => 'Pause Circle',
        'fas fa-stop-circle' => 'Stop Circle',
        'fas fa-forward-step' => 'Skip Forward',
        'fas fa-backward-step' => 'Skip Backward',
        'fas fa-eject' => 'Eject',
        'fas fa-repeat' => 'Repeat',
        'fas fa-shuffle' => 'Shuffle',

        // Volume and Audio Settings
        'fas fa-volume-high' => 'Volume High',
        'fas fa-volume-low' => 'Volume Low',
        'fas fa-volume-off' => 'Volume Off',
        'fas fa-volume-xmark' => 'Volume Mute',
        'fas fa-headphones' => 'Headphones',
        'fas fa-headphones-simple' => 'Headphones Simple',
        'fas fa-microphone' => 'Microphone',
        'fas fa-microphone-slash' => 'Microphone Mute',
        'fas fa-microphone-lines' => 'Microphone Lines',
        'fas fa-wave-square' => 'Wave Square',
        'fas fa-radio' => 'Radio',

        // Video and Media
        'fas fa-video' => 'Video',
        'fas fa-video-slash' => 'Video Off',
        'fas fa-camera' => 'Camera',
        'fas fa-camera-retro' => 'Camera Retro',
        'fas fa-film' => 'Film',
        'fas fa-photo-film' => 'Photo Film',
        'fas fa-clapperboard' => 'Clapperboard',
        'fas fa-file-video' => 'File Video',
        'fas fa-file-audio' => 'File Audio',
        'fas fa-music' => 'Music',
        'fas fa-compact-disc' => 'Compact Disc',
        'fas fa-record-vinyl' => 'Record Vinyl',

        // Casting and Connectivity
        'fa-brands fa-chromecast' => 'Cast',
        'fas fa-wifi' => 'Wi-Fi',
        'fa-brands fa-bluetooth' => 'Bluetooth',
        'fas fa-signal' => 'Signal',
        'fas fa-rss' => 'RSS Feed',
        'fas fa-satellite' => 'Satellite',
        'fas fa-satellite-dish' => 'Satellite Dish',
        'fas fa-tower-broadcast' => 'Broadcast Tower',
        'fas fa-podcast' => 'Podcast',
        'fas fa-desktop' => 'Desktop',
        'fas fa-tv' => 'TV',
        'fas fa-mobile' => 'Mobile',
        'fas fa-mobile-screen' => 'Mobile Screen',

        // Sharing and Social Features
        'fas fa-share' => 'Share',
        'fas fa-share-nodes' => 'Share Nodes',
        'fas fa-share-square' => 'Share Square',
        'fas fa-heart' => 'Heart',
        'fas fa-star' => 'Star',
        'fas fa-thumbs-up' => 'Thumbs Up',
        'fas fa-thumbs-down' => 'Thumbs Down',
        'fas fa-comment' => 'Comment',
        'fas fa-comments' => 'Comments',
        'fas fa-retweet' => 'Retweet',
        'fas fa-reply' => 'Reply',
        'fas fa-reply-all' => 'Reply All',
        'fas fa-envelope' => 'Email',
        'fas fa-link' => 'Link',
        'fas fa-copy' => 'Copy',

        // Tracklist and Navigation
        'fas fa-list' => 'List',
        'fas fa-list-ul' => 'List Unordered',
        'fas fa-list-ol' => 'List Ordered',
        'fas fa-list-check' => 'List Check',
        'fas fa-bars' => 'Bars',
        'fas fa-th-list' => 'Tracklist',
        'fas fa-arrow-left' => 'Arrow Left',
        'fas fa-arrow-right' => 'Arrow Right',
        'fas fa-arrow-up' => 'Arrow Up',
        'fas fa-arrow-down' => 'Arrow Down',
        'fas fa-caret-left' => 'Caret Left',
        'fas fa-caret-right' => 'Caret Right',
        'fas fa-caret-up' => 'Caret Up',
        'fas fa-caret-down' => 'Caret Down',
        'fas fa-angle-left' => 'Angle Left',
        'fas fa-angle-right' => 'Angle Right',
        'fas fa-angle-up' => 'Angle Up',
        'fas fa-angle-down' => 'Angle Down',
        'fas fa-chevron-left' => 'Chevron Left',
        'fas fa-chevron-right' => 'Chevron Right',
        'fas fa-chevron-up' => 'Chevron Up',
        'fas fa-chevron-down' => 'Chevron Down',

        // Popup and Utility Icons
        'fas fa-expand' => 'Expand',
        'fas fa-compress' => 'Compress',
        'fas fa-window-maximize' => 'Window Maximize',
        'fas fa-window-minimize' => 'Window Minimize',
        'fas fa-window-restore' => 'Window Restore',
        'fas fa-window-close' => 'Window Close',
        'fas fa-arrow-pointer' => 'Arrow Pointer',
        'fas fa-search' => 'Search',
        'fas fa-magnifying-glass' => 'Magnifying Glass',
        'fas fa-magnifying-glass-plus' => 'Zoom In',
        'fas fa-magnifying-glass-minus' => 'Zoom Out',
        'fas fa-plus' => 'Plus',
        'fas fa-minus' => 'Minus',
        'fas fa-times' => 'Times',
        'fas fa-xmark' => 'X Mark',
        'fas fa-check' => 'Check',
        'fas fa-info' => 'Info',
        'fas fa-info-circle' => 'Info Circle',
        'fas fa-question' => 'Question',
        'fas fa-question-circle' => 'Question Circle',
        'fas fa-exclamation' => 'Exclamation',
        'fas fa-exclamation-circle' => 'Exclamation Circle',

        // Media Editing and Tools
        'fas fa-crop' => 'Crop',
        'fas fa-crop-simple' => 'Crop Simple',
        'fas fa-cut' => 'Cut',
        'fas fa-scissors' => 'Scissors',
        'fas fa-paste' => 'Paste',
        'fas fa-rotate' => 'Rotate',
        'fas fa-rotate-left' => 'Rotate Left',
        'fas fa-rotate-right' => 'Rotate Right',
        'fas fa-sliders' => 'Sliders',
        'fas fa-sliders-h' => 'Sliders Horizontal',
        'fas fa-gauge' => 'Gauge',
        'fas fa-gauge-high' => 'Gauge High',
        'fas fa-gauge-simple' => 'Gauge Simple',
        'fas fa-wrench' => 'Wrench',
        'fas fa-gear' => 'Gear',
        'fas fa-gears' => 'Gears',

        // File and Storage
        'fas fa-file' => 'File',
        'fas fa-file-import' => 'File Import',
        'fas fa-file-export' => 'File Export',
        'fas fa-file-download' => 'File Download',
        'fas fa-file-upload' => 'File Upload',
        'fas fa-download' => 'Download',
        'fas fa-upload' => 'Upload',
        'fas fa-cloud' => 'Cloud',
        'fas fa-cloud-download' => 'Cloud Download',
        'fas fa-cloud-upload' => 'Cloud Upload',
        'fas fa-save' => 'Save',
        'fas fa-floppy-disk' => 'Floppy Disk',
        'fas fa-folder' => 'Folder',
        'fas fa-folder-open' => 'Folder Open',

        // Playback Speed and Settings
        'fas fa-clock' => 'Clock',
        'fas fa-stopwatch' => 'Stopwatch',
        'fas fa-hourglass' => 'Hourglass',
        'fas fa-hourglass-start' => 'Hourglass Start',
        'fas fa-hourglass-end' => 'Hourglass End',
        'fas fa-history' => 'History',
        'fas fa-sync' => 'Sync',
        'fas fa-sync-alt' => 'Sync Alt',
        'fas fa-undo' => 'Undo',
        'fas fa-redo' => 'Redo',

        // Miscellaneous Media Icons
        'fas fa-bell' => 'Bell',
        'fas fa-bell-slash' => 'Bell Slash',
        'fas fa-bookmark' => 'Bookmark',
        'fas fa-tag' => 'Tag',
        'fas fa-tags' => 'Tags',
        'fas fa-trash' => 'Trash',
        'fas fa-trash-alt' => 'Trash Alt',
        'fas fa-eye' => 'Eye',
        'fas fa-eye-slash' => 'Eye Slash',
        'fas fa-lock' => 'Lock',
        'fas fa-unlock' => 'Unlock',
        'fas fa-user' => 'User',
        'fas fa-users' => 'Users',
        'fas fa-user-plus' => 'User Plus',
        'fas fa-user-minus' => 'User Minus',
        'fas fa-user-circle' => 'User Circle',
        'fas fa-sign-in' => 'Sign In',
        'fas fa-sign-out' => 'Sign Out',
        'fas fa-power-off' => 'Power Off',
        'fas fa-toggle-on' => 'Toggle On',
        'fas fa-toggle-off' => 'Toggle Off',
        'fas fa-circle-play' => 'Circle Play',
        'fas fa-circle-pause' => 'Circle Pause',
        'fas fa-circle-stop' => 'Circle Stop',
        'fas fa-headset' => 'Headset',
        'fas fa-volume-mute' => 'Volume Mute Alt',
        'fas fa-file-waveform' => 'File Waveform',
        'fas fa-tachometer-alt' => 'Tachometer Alt',
        'fas fa-bolt' => 'Bolt',
        'fas fa-circle' => 'Circle',
        'fas fa-square' => 'Square',
        'fas fa-image' => 'Image',
        'fas fa-images' => 'Images',
        'fas fa-photo-video' => 'Photo Video',
        'fas fa-calendar' => 'Calendar',
        'fas fa-calendar-alt' => 'Calendar Alt',
        'fas fa-clock-rotate-left' => 'Clock Rotate Left',
        'fas fa-arrow-rotate-left' => 'Arrow Rotate Left',
        'fas fa-arrow-rotate-right' => 'Arrow Rotate Right',
        'fas fa-arrows-rotate' => 'Arrows Rotate',
        'fas fa-filter' => 'Filter',
        'fas fa-sort' => 'Sort',
        'fas fa-sort-up' => 'Sort Up',
        'fas fa-sort-down' => 'Sort Down',
        'fas fa-random' => 'Random',
        'fas fa-arrows-alt' => 'Arrows Alt',
        'fas fa-arrows-alt-h' => 'Arrows Horizontal',
        'fas fa-arrows-alt-v' => 'Arrows Vertical',
        'fas fa-closed-captioning' => 'Closed Captioning',
        'fas fa-audio-description' => 'Audio Description',
        'fas fa-language' => 'Language',
        'fas fa-globe' => 'Globe',
        'fas fa-map' => 'Map',
        'fas fa-location-arrow' => 'Location Arrow',
        'fas fa-thumbtack' => 'Thumbtack',
        'fas fa-paperclip' => 'Paperclip',
        'fas fa-print' => 'Print',
        'fas fa-ruler' => 'Ruler',
        'fas fa-ruler-horizontal' => 'Ruler Horizontal',
        'fas fa-ruler-vertical' => 'Ruler Vertical',
        'fas fa-pen' => 'Pen',
        'fas fa-pencil' => 'Pencil',
        'fas fa-edit' => 'Edit',
        'fas fa-highlighter' => 'Highlighter',
        'fas fa-eraser' => 'Eraser',
        'fas fa-palette' => 'Palette',
        'fas fa-paint-brush' => 'Paint Brush',
        'fas fa-paint-roller' => 'Paint Roller',
        'fas fa-brush' => 'Brush',
        'fas fa-fill' => 'Fill',
        'fas fa-fill-drip' => 'Fill Drip',
        'fas fa-swatchbook' => 'Swatchbook',
        'fas fa-tint' => 'Tint',
        'fas fa-tint-slash' => 'Tint Slash',
        'fas fa-eye-dropper' => 'Eye Dropper',
        'fas fa-adjust' => 'Adjust',
        'fas fa-brush' => 'Brush Alt',
        'fas fa-border-all' => 'Border All',
        'fas fa-border-none' => 'Border None',
        'fas fa-border-top-left' => 'Border Top Left',
        'fas fa-align-left' => 'Align Left',
        'fas fa-align-center' => 'Align Center',
        'fas fa-align-right' => 'Align Right',
        'fas fa-align-justify' => 'Align Justify',
        'fas fa-indent' => 'Indent',
        'fas fa-outdent' => 'Outdent',
        'fas fa-text-height' => 'Text Height',
        'fas fa-text-width' => 'Text Width',
        'fas fa-font' => 'Font',
        'fas fa-bold' => 'Bold',
        'fas fa-italic' => 'Italic',
        'fas fa-underline' => 'Underline',
        'fas fa-strikethrough' => 'Strikethrough',
        'fas fa-superscript' => 'Superscript',
        'fas fa-subscript' => 'Subscript',
        'fas fa-list-alt' => 'List Alt',
        'fas fa-table' => 'Table',
        'fas fa-columns' => 'Columns',
        'fas fa-th' => 'Thumbnails',
        'fas fa-th-large' => 'Thumbnails Large',
    ];
}